-- EDA
SELECT DISTINCT repair_status from warrantys;

SELECT * FROM category;

-- PERFORMANCE QUERIES

SET STATISTICS TIME ON;

SELECT * 
FROM SALE
WHERE PRODUCT_ID = 'P-44';

SET STATISTICS TIME OFF;

-- CREATE INDEX SALE
CREATE INDEX SALE_PRODUCT_ID ON SALE(PRODUCT_ID);


SET STATISTICS TIME ON;
SELECT * 
FROM SALE
WHERE STORE_ID = 'ST-31'
SET STATISTICS TIME OFF;


-- CREATE INDEX SALE
CREATE INDEX SALE_PRODUCT_ID ON SALE(PRODUCT_ID);


-- CREATE INDEX SALE
CREATE INDEX SALE_STORE_ID ON SALE(STORE_ID);

-- 36MS > 15MS

-- CREATE INDEX SALE
CREATE INDEX SALE_DATE ON SALE(SALE_DATE);

-- BUSINESS PROBLEM

-- 1. FIND THE NUMBER OF STORES IN EACH COUNTRY
SELECT COUNTRY,COUNT(STORE_ID) AS NUMBER_STORE_COUNTRY
FROM STORES
GROUP BY COUNTRY
ORDER BY NUMBER_STORE_COUNTRY ASC

-- 2. TOTAL NUMBER OF UNIT SOLD BY EACH STORE
SELECT S.STORE_ID,
		ST.STORE_NAME, SUM(S.QUANTITY) AS TOTAL_UNIT_SOLD
FROM SALE S
JOIN STORES ST
ON ST.STORE_ID = S.STORE_ID
GROUP BY S.STORE_ID,ST.STORE_NAME
ORDER BY TOTAL_UNIT_SOLD ASC

-- 3. HOW MANY SALES OCCURED IN DECEMBER 2023
SELECT COUNT(SALE_ID) AS TOTAL_SALE
FROM SALE
WHERE FORMAT(SALE_DATE, 'MM-yyyy') = '12-2023'

-- 4. DETERMINE HOW MANY STORES HAVE NEVER HAD A WARRANTY CLAIM FILED
SELECT COUNT(*) FROM STORES WHERE STORE_ID 
NOT IN  (SELECT DISTINCT STORE_ID
		FROM SALE S
		RIGHT JOIN warrantys W
		ON S.sale_id = W.sale_id
		);

-- 5. CALCULATE THE PERCENTAGE OF WARRANTY CLAIM MARKED AS 'REJECTED' 
WITH RejectedWarranties AS (
    SELECT COUNT(*) AS TOTAL_REJECTED
    FROM warrantys
    WHERE repair_status = 'REJECTED'
),
TotalWarranties AS (
    SELECT COUNT(*) AS TOTAL_WARRANTIES
    FROM warrantys
)
SELECT 
    COALESCE(ROUND(CAST(rw.TOTAL_REJECTED AS FLOAT) / NULLIF(tw.TOTAL_WARRANTIES, 0), 2), 0) * 100 AS PERCENTAGE_REJECTED
FROM RejectedWarranties rw, TotalWarranties tw;



